# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day)
  schedule:  []
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GHUB_PUBLIC_ACCESS_TOKEN }}

          # Options
          user: omkar-tenkale
          template: classic
          base: header, activity, community
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_calendar: no
          plugin_calendar_limit: 3
          plugin_discussions: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_people_types: followers, following
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 9752209
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
